use 25.08 versions of RAPIDS CI workflows (#126)
#50 removed uploads of conda packages / wheels to S3 on `branch-25.08`

Unfortunately, some publishing workflows on this branch are using a version of GitHub Actions workflows that expects to be able to download packages from S3, resulting in failures like this:

```text
jq: error (at <unknown>): Cannot iterate over null (null)
Using Anaconda API: https://api.anaconda.org/
Using "rapidsai-wheels-nightly" as upload username
Error:  File "./dist/*.whl" does not exist
Error:  File "./dist/*.whl" does not exist
```

([build link](https://github.com/NVIDIA/cuopt/actions/runs/15853760492/job/44695835791))

This fixes that, by updating to `branch-25.08` of https://github.com/rapidsai/shared-workflows.

## Notes for Reviewers

### Why just the publishing workflows?

All other workflows are already using `branch-25.08`... looks like just this small set was missed (or maybe accidentally overwritten by a bad merge conflict resolution or something).

### Issue

N/A

#

Authors:
  - James Lamb (https://github.com/jameslamb)
  - Ramakrishnap (https://github.com/rgsl888prabhu)

Approvers:
  - Ramakrishnap (https://github.com/rgsl888prabhu)
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/NVIDIA/cuopt/pull/126